name: "Continuous Integration"

on:
  ["pull_request", "push", "workflow_dispatch"]

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        deps:
          - "normal"
        include:
          - deps: "low"
            php-version: "7.4"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup PHP ${{ matrix.php-version }}"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: "Get composer cache directory"
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache composer dependencies"
        uses: actions/cache@v2
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: "Install dependencies with Composer"
        run: "composer install --no-interaction --no-progress --prefer-dist"

      - name: "Update lowest dependencies with Composer"
        run: "composer update --prefer-dist --prefer-lowest"
        if: "${{ matrix.deps == 'low' }}"

      - name: "Run PHPUnit"
        run: "./vendor/bin/phpunit"

      - name: "Run demo"
        run: "php ./demo/run.php"
